// mdcms service worker — generated by mdcms build
const CACHE_NAME = 'mdcms-afd0a4d3';
const PRECACHE_URLS = [
  "index.html",
  "config.yml",
  "nav.yml",
  "search.json",
  "theme.yml",
  "pages/home.md",
  "pages/wrsrcli/commands.md",
  "pages/wrsrcli/commands.md.backup",
  "pages/wrsrcli/installation.md",
  "pages/wrsrcli/installation.md.backup",
  "pages/wrsrcli/introduction.md",
  "pages/wrsrcli/introduction.md.backup",
  "assets/icons/arrow_drop_down.svg",
  "assets/icons/arrow_right.svg",
  "assets/icons/dark_mode.svg",
  "assets/icons/error.svg",
  "assets/icons/info.svg",
  "assets/icons/keyboard_arrow_right.svg",
  "assets/icons/left_panel_close.svg",
  "assets/icons/left_panel_open.svg",
  "assets/icons/light_mode.svg",
  "assets/icons/menu.svg",
  "assets/icons/right_panel_close.svg",
  "assets/icons/right_panel_open.svg",
  "assets/icons/search.svg",
  "assets/icons/success.svg",
  "assets/icons/warning.svg",
  "assets/images/favicon.png"
];

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => cache.addAll(PRECACHE_URLS))
  );
  self.skipWaiting();
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k)))
    )
  );
  self.clients.claim();
});

self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  event.respondWith(
    caches.match(event.request).then(cached => cached || fetch(event.request))
  );
});
